// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"

	"github.com/kubeflow/spark-operator/v2/api/v1beta2"
	"github.com/slackhq/spark-gateway/internal/domain"
)

// Ensure, that SparkApplicationServiceMock does implement SparkApplicationService.
// If this is not the case, regenerate this file with moq.
var _ SparkApplicationService = &SparkApplicationServiceMock{}

// SparkApplicationServiceMock is a mock implementation of SparkApplicationService.
//
//	func TestSomethingThatUsesSparkApplicationService(t *testing.T) {
//
//		// make and configure a mocked SparkApplicationService
//		mockedSparkApplicationService := &SparkApplicationServiceMock{
//			CreateFunc: func(ctx context.Context, application *v1beta2.SparkApplication, user string) (*domain.GatewayApplication, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, gatewayId string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, gatewayId string) (*domain.GatewayApplication, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, cluster string, namespace string) ([]*domain.GatewayApplicationMeta, error) {
//				panic("mock out the List method")
//			},
//			LogsFunc: func(ctx context.Context, gatewayId string, tailLines int) (*string, error) {
//				panic("mock out the Logs method")
//			},
//			StatusFunc: func(ctx context.Context, gatewayId string) (*v1beta2.SparkApplicationStatus, error) {
//				panic("mock out the Status method")
//			},
//		}
//
//		// use mockedSparkApplicationService in code that requires SparkApplicationService
//		// and then make assertions.
//
//	}
type SparkApplicationServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, application *v1beta2.SparkApplication, user string) (*domain.GatewayApplication, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, gatewayId string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, gatewayId string) (*domain.GatewayApplication, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, cluster string, namespace string) ([]*domain.GatewayApplicationMeta, error)

	// LogsFunc mocks the Logs method.
	LogsFunc func(ctx context.Context, gatewayId string, tailLines int) (*string, error)

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context, gatewayId string) (*v1beta2.SparkApplicationStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Application is the application argument value.
			Application *v1beta2.SparkApplication
			// User is the user argument value.
			User string
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster string
			// Namespace is the namespace argument value.
			Namespace string
		}
		// Logs holds details about calls to the Logs method.
		Logs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayId is the gatewayId argument value.
			GatewayId string
			// TailLines is the tailLines argument value.
			TailLines int
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// GatewayId is the gatewayId argument value.
			GatewayId string
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockLogs   sync.RWMutex
	lockStatus sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SparkApplicationServiceMock) Create(ctx context.Context, application *v1beta2.SparkApplication, user string) (*domain.GatewayApplication, error) {
	if mock.CreateFunc == nil {
		panic("SparkApplicationServiceMock.CreateFunc: method is nil but SparkApplicationService.Create was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Application *v1beta2.SparkApplication
		User        string
	}{
		Ctx:         ctx,
		Application: application,
		User:        user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, application, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSparkApplicationService.CreateCalls())
func (mock *SparkApplicationServiceMock) CreateCalls() []struct {
	Ctx         context.Context
	Application *v1beta2.SparkApplication
	User        string
} {
	var calls []struct {
		Ctx         context.Context
		Application *v1beta2.SparkApplication
		User        string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *SparkApplicationServiceMock) Delete(ctx context.Context, gatewayId string) error {
	if mock.DeleteFunc == nil {
		panic("SparkApplicationServiceMock.DeleteFunc: method is nil but SparkApplicationService.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayId string
	}{
		Ctx:       ctx,
		GatewayId: gatewayId,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, gatewayId)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedSparkApplicationService.DeleteCalls())
func (mock *SparkApplicationServiceMock) DeleteCalls() []struct {
	Ctx       context.Context
	GatewayId string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayId string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SparkApplicationServiceMock) Get(ctx context.Context, gatewayId string) (*domain.GatewayApplication, error) {
	if mock.GetFunc == nil {
		panic("SparkApplicationServiceMock.GetFunc: method is nil but SparkApplicationService.Get was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayId string
	}{
		Ctx:       ctx,
		GatewayId: gatewayId,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, gatewayId)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSparkApplicationService.GetCalls())
func (mock *SparkApplicationServiceMock) GetCalls() []struct {
	Ctx       context.Context
	GatewayId string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayId string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *SparkApplicationServiceMock) List(ctx context.Context, cluster string, namespace string) ([]*domain.GatewayApplicationMeta, error) {
	if mock.ListFunc == nil {
		panic("SparkApplicationServiceMock.ListFunc: method is nil but SparkApplicationService.List was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   string
		Namespace string
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, cluster, namespace)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedSparkApplicationService.ListCalls())
func (mock *SparkApplicationServiceMock) ListCalls() []struct {
	Ctx       context.Context
	Cluster   string
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   string
		Namespace string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Logs calls LogsFunc.
func (mock *SparkApplicationServiceMock) Logs(ctx context.Context, gatewayId string, tailLines int) (*string, error) {
	if mock.LogsFunc == nil {
		panic("SparkApplicationServiceMock.LogsFunc: method is nil but SparkApplicationService.Logs was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayId string
		TailLines int
	}{
		Ctx:       ctx,
		GatewayId: gatewayId,
		TailLines: tailLines,
	}
	mock.lockLogs.Lock()
	mock.calls.Logs = append(mock.calls.Logs, callInfo)
	mock.lockLogs.Unlock()
	return mock.LogsFunc(ctx, gatewayId, tailLines)
}

// LogsCalls gets all the calls that were made to Logs.
// Check the length with:
//
//	len(mockedSparkApplicationService.LogsCalls())
func (mock *SparkApplicationServiceMock) LogsCalls() []struct {
	Ctx       context.Context
	GatewayId string
	TailLines int
} {
	var calls []struct {
		Ctx       context.Context
		GatewayId string
		TailLines int
	}
	mock.lockLogs.RLock()
	calls = mock.calls.Logs
	mock.lockLogs.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *SparkApplicationServiceMock) Status(ctx context.Context, gatewayId string) (*v1beta2.SparkApplicationStatus, error) {
	if mock.StatusFunc == nil {
		panic("SparkApplicationServiceMock.StatusFunc: method is nil but SparkApplicationService.Status was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		GatewayId string
	}{
		Ctx:       ctx,
		GatewayId: gatewayId,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx, gatewayId)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//
//	len(mockedSparkApplicationService.StatusCalls())
func (mock *SparkApplicationServiceMock) StatusCalls() []struct {
	Ctx       context.Context
	GatewayId string
} {
	var calls []struct {
		Ctx       context.Context
		GatewayId string
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}
