// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"github.com/kubeflow/spark-operator/v2/api/v1beta2"
	"github.com/slackhq/spark-gateway/internal/domain"
	"sync"
)

// Ensure, that GatewayApplicationRepositoryMock does implement GatewayApplicationRepository.
// If this is not the case, regenerate this file with moq.
var _ GatewayApplicationRepository = &GatewayApplicationRepositoryMock{}

// GatewayApplicationRepositoryMock is a mock implementation of GatewayApplicationRepository.
//
//	func TestSomethingThatUsesGatewayApplicationRepository(t *testing.T) {
//
//		// make and configure a mocked GatewayApplicationRepository
//		mockedGatewayApplicationRepository := &GatewayApplicationRepositoryMock{
//			CreateFunc: func(ctx context.Context, cluster domain.KubeCluster, application *v1beta2.SparkApplication) (*v1beta2.SparkApplication, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplication, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, cluster domain.KubeCluster, namespace string) ([]*domain.SparkManagerSparkApplicationSummary, error) {
//				panic("mock out the List method")
//			},
//			LogsFunc: func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string, tailLines int) (*string, error) {
//				panic("mock out the Logs method")
//			},
//			StatusFunc: func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplicationStatus, error) {
//				panic("mock out the Status method")
//			},
//		}
//
//		// use mockedGatewayApplicationRepository in code that requires GatewayApplicationRepository
//		// and then make assertions.
//
//	}
type GatewayApplicationRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, cluster domain.KubeCluster, application *v1beta2.SparkApplication) (*v1beta2.SparkApplication, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplication, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, cluster domain.KubeCluster, namespace string) ([]*domain.SparkManagerSparkApplicationSummary, error)

	// LogsFunc mocks the Logs method.
	LogsFunc func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string, tailLines int) (*string, error)

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplicationStatus, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Application is the application argument value.
			Application *v1beta2.SparkApplication
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Namespace is the namespace argument value.
			Namespace string
		}
		// Logs holds details about calls to the Logs method.
		Logs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
			// TailLines is the tailLines argument value.
			TailLines int
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cluster is the cluster argument value.
			Cluster domain.KubeCluster
			// Namespace is the namespace argument value.
			Namespace string
			// Name is the name argument value.
			Name string
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockLogs   sync.RWMutex
	lockStatus sync.RWMutex
}

// Create calls CreateFunc.
func (mock *GatewayApplicationRepositoryMock) Create(ctx context.Context, cluster domain.KubeCluster, application *v1beta2.SparkApplication) (*v1beta2.SparkApplication, error) {
	if mock.CreateFunc == nil {
		panic("GatewayApplicationRepositoryMock.CreateFunc: method is nil but GatewayApplicationRepository.Create was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Cluster     domain.KubeCluster
		Application *v1beta2.SparkApplication
	}{
		Ctx:         ctx,
		Cluster:     cluster,
		Application: application,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, cluster, application)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.CreateCalls())
func (mock *GatewayApplicationRepositoryMock) CreateCalls() []struct {
	Ctx         context.Context
	Cluster     domain.KubeCluster
	Application *v1beta2.SparkApplication
} {
	var calls []struct {
		Ctx         context.Context
		Cluster     domain.KubeCluster
		Application *v1beta2.SparkApplication
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *GatewayApplicationRepositoryMock) Delete(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) error {
	if mock.DeleteFunc == nil {
		panic("GatewayApplicationRepositoryMock.DeleteFunc: method is nil but GatewayApplicationRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, cluster, namespace, name)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.DeleteCalls())
func (mock *GatewayApplicationRepositoryMock) DeleteCalls() []struct {
	Ctx       context.Context
	Cluster   domain.KubeCluster
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *GatewayApplicationRepositoryMock) Get(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplication, error) {
	if mock.GetFunc == nil {
		panic("GatewayApplicationRepositoryMock.GetFunc: method is nil but GatewayApplicationRepository.Get was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, cluster, namespace, name)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.GetCalls())
func (mock *GatewayApplicationRepositoryMock) GetCalls() []struct {
	Ctx       context.Context
	Cluster   domain.KubeCluster
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *GatewayApplicationRepositoryMock) List(ctx context.Context, cluster domain.KubeCluster, namespace string) ([]*domain.SparkManagerSparkApplicationSummary, error) {
	if mock.ListFunc == nil {
		panic("GatewayApplicationRepositoryMock.ListFunc: method is nil but GatewayApplicationRepository.List was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, cluster, namespace)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.ListCalls())
func (mock *GatewayApplicationRepositoryMock) ListCalls() []struct {
	Ctx       context.Context
	Cluster   domain.KubeCluster
	Namespace string
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Logs calls LogsFunc.
func (mock *GatewayApplicationRepositoryMock) Logs(ctx context.Context, cluster domain.KubeCluster, namespace string, name string, tailLines int) (*string, error) {
	if mock.LogsFunc == nil {
		panic("GatewayApplicationRepositoryMock.LogsFunc: method is nil but GatewayApplicationRepository.Logs was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
		TailLines int
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
		Name:      name,
		TailLines: tailLines,
	}
	mock.lockLogs.Lock()
	mock.calls.Logs = append(mock.calls.Logs, callInfo)
	mock.lockLogs.Unlock()
	return mock.LogsFunc(ctx, cluster, namespace, name, tailLines)
}

// LogsCalls gets all the calls that were made to Logs.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.LogsCalls())
func (mock *GatewayApplicationRepositoryMock) LogsCalls() []struct {
	Ctx       context.Context
	Cluster   domain.KubeCluster
	Namespace string
	Name      string
	TailLines int
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
		TailLines int
	}
	mock.lockLogs.RLock()
	calls = mock.calls.Logs
	mock.lockLogs.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *GatewayApplicationRepositoryMock) Status(ctx context.Context, cluster domain.KubeCluster, namespace string, name string) (*v1beta2.SparkApplicationStatus, error) {
	if mock.StatusFunc == nil {
		panic("GatewayApplicationRepositoryMock.StatusFunc: method is nil but GatewayApplicationRepository.Status was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}{
		Ctx:       ctx,
		Cluster:   cluster,
		Namespace: namespace,
		Name:      name,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx, cluster, namespace, name)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//
//	len(mockedGatewayApplicationRepository.StatusCalls())
func (mock *GatewayApplicationRepositoryMock) StatusCalls() []struct {
	Ctx       context.Context
	Cluster   domain.KubeCluster
	Namespace string
	Name      string
} {
	var calls []struct {
		Ctx       context.Context
		Cluster   domain.KubeCluster
		Namespace string
		Name      string
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}
