// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	v1beta2 "github.com/kubeflow/spark-operator/v2/api/v1beta2"
)

type LivyApplication struct {
	BatchID int64  `json:"batch_id"`
	Uid     string `json:"uid"`
}

type SparkApplication struct {
	Uid             uuid.UUID                       `json:"uid"`
	Name            *string                         `json:"name"`
	CreationTime    *time.Time                      `json:"creation_time"`
	TerminationTime *time.Time                      `json:"termination_time"`
	Username        *string                         `json:"username"`
	Namespace       *string                         `json:"namespace"`
	Cluster         *string                         `json:"cluster"`
	Submitted       *v1beta2.SparkApplication       `json:"submitted"`
	Updated         *v1beta2.SparkApplication       `json:"updated"`
	State           *string                         `json:"state"`
	Status          *v1beta2.SparkApplicationStatus `json:"status"`
}
