name: build-main

on:
  push:
    branches:
      - main

env:
  REPOSITORY: spark-gateway
  TAG: latest

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.REPOSITORY }}:${{ env.TAG }}
