# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continuous Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Swagger Docs Diff Check
        run: |
          set -eu
          
          go install github.com/swaggo/swag/cmd/swag@latest
          SWAG_INIT_CMD="swag init -d ./internal/gateway/api/v1/kubeflow -g handler.go -o ./docs/swagger --parseDependency --parseInternal"
          eval "$SWAG_INIT_CMD"
          
          # Check diff
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: Swagger Docs diff detected."
            echo "Regenerate docs by running: ${SWAG_INIT_CMD}"
            exit 1
          fi
